<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">prepareNameWithDelimiter</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCXRpdGxlID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJz
b3IsICJ0aXRsZSIgKTsNCglTdHJpbmcJZmlyc3RuYW1lID0gSURhdGFVdGlsLmdldFN0cmluZygg
cGlwZWxpbmVDdXJzb3IsICJmaXJzdG5hbWUiICk7DQoJU3RyaW5nCXN1cm5hbWUgPSBJRGF0YVV0
aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInN1cm5hbWUiICk7DQpwaXBlbGluZUN1cnNv
ci5kZXN0cm95KCk7DQoNCmlmKHRpdGxlID09IG51bGwgfHwgdGl0bGUuaXNFbXB0eSgpKQ0Kew0K
CXRpdGxlPSIgIjsNCn0NCmlmKGZpcnN0bmFtZSA9PSBudWxsIHx8IGZpcnN0bmFtZS5pc0VtcHR5
KCkpDQp7DQoJZmlyc3RuYW1lPSIgIjsNCn0NCmlmKHN1cm5hbWUgPT0gbnVsbCB8fCBzdXJuYW1l
LmlzRW1wdHkoKSkNCnsNCglzdXJuYW1lID0gIiAiOw0KfQ0KDQpTdHJpbmcgbmFtZURlbGltaXRl
ciA9IHRpdGxlICsiKyIrZmlyc3RuYW1lKyIrIitzdXJuYW1lOw0KLy8gcGlwZWxpbmUNCklEYXRh
Q3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRp
bC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJuYW1lRGVsaW1pdGVyIiwgbmFtZURlbGltaXRlciAp
Ow0KcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7DQoJ</value>
</Values>
